# Generated by Django 4.2.11 on 2024-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_name',
            new_name='name',
        ),
    ]
