# Generated by Django 4.2.11 on 2024-04-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='products',
            new_name='product',
        ),
    ]
