# Generated by Django 4.2.11 on 2024-04-07 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_product_bill_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
